extends Node

signal language_changed
signal volume_changed

const SAVE_PATH := "user://settings.cfg"
const LANGUAGES: Dictionary = {&"en": "English", &"ru": "Русский"}

var _config := ConfigFile.new()
var _lang: String = "en"
var _fullscreen: bool = false
var _volume: float = 80.0
var _screen_shake: float = 100.0
var _vsync: bool = true
var _ui_scale: float = 1.0

var _translations: Dictionary = {}

func _ready() -> void:
	_init_translations()
	_load()
	_apply_all()

func get_language() -> String:
	return _lang

func get_fullscreen() -> bool:
	return _fullscreen

func get_volume() -> float:
	return _volume

func get_screen_shake() -> float:
	return _screen_shake

func get_vsync() -> bool:
	return _vsync

func get_ui_scale() -> float:
	return _ui_scale

func font_size(base: int) -> int:
	return int(base * _ui_scale)

func set_language(lang: String) -> void:
	if lang == _lang or not LANGUAGES.has(lang):
		return
	_lang = lang
	_save()
	language_changed.emit()

func set_fullscreen(value: bool) -> void:
	_fullscreen = value
	if value:
		DisplayServer.window_set_mode(DisplayServer.WINDOW_MODE_FULLSCREEN)
	else:
		DisplayServer.window_set_mode(DisplayServer.WINDOW_MODE_WINDOWED)
	_save()

func set_volume(value: float) -> void:
	_volume = value
	var bus_idx := AudioServer.get_bus_index("Master")
	AudioServer.set_bus_volume_db(bus_idx, linear_to_db(value / 100.0))
	volume_changed.emit()
	_save()

func set_screen_shake(value: float) -> void:
	_screen_shake = value
	_save()

func set_vsync(value: bool) -> void:
	_vsync = value
	if value:
		DisplayServer.window_set_vsync_mode(DisplayServer.VSYNC_ENABLED)
	else:
		DisplayServer.window_set_vsync_mode(DisplayServer.VSYNC_DISABLED)
	_save()

func set_ui_scale(value: float) -> void:
	_ui_scale = clampf(value, 0.75, 1.5)
	_save()

func t(key: StringName) -> String:
	if _translations.has(key) and _translations[key].has(_lang):
		return _translations[key][_lang]
	if _translations.has(key) and _translations[key].has("en"):
		return _translations[key]["en"]
	return String(key)

func _load() -> void:
	if _config.load(SAVE_PATH) != OK:
		return
	_lang = _config.get_value("settings", "language", "en")
	if not LANGUAGES.has(_lang):
		_lang = "en"
	_fullscreen = _config.get_value("settings", "fullscreen", false)
	_volume = _config.get_value("settings", "volume", 80.0)
	_screen_shake = _config.get_value("settings", "screen_shake", 100.0)
	_vsync = _config.get_value("settings", "vsync", true)
	_ui_scale = _config.get_value("settings", "ui_scale", 1.0)

func _save() -> void:
	_config.set_value("settings", "language", _lang)
	_config.set_value("settings", "fullscreen", _fullscreen)
	_config.set_value("settings", "volume", _volume)
	_config.set_value("settings", "screen_shake", _screen_shake)
	_config.set_value("settings", "vsync", _vsync)
	_config.set_value("settings", "ui_scale", _ui_scale)
	_config.save(SAVE_PATH)

func _apply_all() -> void:
	set_fullscreen(_fullscreen)
	set_volume(_volume)
	set_vsync(_vsync)

func _init_translations() -> void:
	_add(&"menu_title", "MAGIC SURVIVAL", "MAGIC SURVIVAL")
	_add(&"menu_subtitle", "Echoes of Arcana", "Эхо Арканы")
	_add(&"btn_play", "▶  BEGIN", "▶  НАЧАТЬ")
	_add(&"btn_settings", "⚙  SETTINGS", "⚙  НАСТРОЙКИ")
	_add(&"btn_exit", "✕  DEPART", "✕  ВЫХОД")

	_add(&"settings_title", "✦  SETTINGS  ✦", "✦  НАСТРОЙКИ  ✦")
	_add(&"opt_fullscreen", "Fullscreen", "Полный экран")
	_add(&"opt_volume", "Master Volume", "Общая громкость")
	_add(&"opt_language", "Language", "Язык")
	_add(&"opt_shake", "Screen Shake", "Тряска экрана")
	_add(&"opt_vsync", "VSync", "Верт. синхронизация")
	_add(&"opt_ui_scale", "UI Scale", "Масштаб интерфейса")
	_add(&"btn_return", "←  RETURN", "←  НАЗАД")

	_add(&"pause_title", "✦  PAUSED  ✦", "✦  ПАУЗА  ✦")
	_add(&"btn_resume", "▶  RESUME", "▶  ПРОДОЛЖИТЬ")
	_add(&"btn_stats", "✦  STATS", "✦  СТАТЫ")
	_add(&"btn_abandon", "✕  ABANDON", "✕  ПОКИНУТЬ")
	_add(&"pause_continue", "▶  CONTINUE  ▶", "▶  ПРОДОЛЖИТЬ  ▶")
	_add(&"confirm_exit_title", "End your run?", "Закончить забег?")
	_add(&"confirm_exit_msg", "Your results will be shown.", "Результаты будут показаны.")
	_add(&"confirm_exit_yes", "END RUN", "ЗАКОНЧИТЬ")
	_add(&"pause_summary", "Level %d  |  %s  |  %d kills", "Уровень %d  |  %s  |  %d убийств")

	_add(&"go_title", "FALLEN", "ПАВШИЙ")
	_add(&"go_subtitle", "Your journey has ended", "Твоё путешествие окончено")
	_add(&"btn_restart", "▶  RISE AGAIN", "▶  ВОЗРОДИТЬСЯ")
	_add(&"btn_return_menu", "✕  RETURN", "✕  В МЕНЮ")
	_add(&"victory_title", "SURVIVED", "ВЫЖИЛ")
	_add(&"victory_subtitle", "You endured the arcane onslaught", "Ты выдержал арканный натиск")
	_add(&"btn_continue_endless", "⟳  ENDLESS", "⟳  БЕСКОНЕЧНО")
	_add(&"stat_time", "Survived", "Выживание")
	_add(&"stat_kills", "Slain", "Убито")
	_add(&"stat_level", "Attained  Level", "Достигнут уровень")

	_add(&"lu_title", "Выбор заклинания", "Выбор заклинания")
	_add(&"lu_current_level", "Текущий уровень : %d", "Текущий уровень : %d")
	_add(&"lu_subtitle", "Choose your path", "Выбери свой путь")
	_add(&"btn_mana_return", "✦  RETURN %d%% XP", "✦  ВЕРНУТЬ %d%% ОПЫТА")
	_add(&"btn_mana_return_disabled", "✦  NO XP RETURN", "✦  ВОЗВРАТ НЕВОЗМОЖЕН")

	_add(&"stats_title", "✦  ARCANE STATS  ✦", "✦  АРКАННЫЕ СТАТЫ  ✦")
	_add(&"spells_title", "✦  SPELLS  ✦", "✦  ЗАКЛИНАНИЯ  ✦")
	_add(&"spell_no_mod", "No modification", "Без модификации")
	_add(&"spells_empty", "No spells acquired yet", "Заклинания ещё не получены")

	_add(&"pause_artifacts", "✦  ARTIFACTS  ✦", "✦  АРТЕФАКТЫ  ✦")
	_add(&"artifact_slots_title", "✦  ARTIFACTS  ✦", "✦  АРТЕФАКТЫ  ✦")
	_add(&"artifact_empty", "No spells acquired yet", "Артефакты ещё не получены")

	_add(&"run_summary_title", "✦  RUN SUMMARY  ✦", "✦  ИТОГИ ЗАБЕГА  ✦")
	_add(&"run_summary_time", "Time", "Время")
	_add(&"run_summary_kills", "Kills", "Убийства")
	_add(&"run_summary_damage", "Damage by Spell", "Урон по заклинаниям")
	_add(&"run_summary_combo", "Max Combo", "Макс. комбо")
	_add(&"run_summary_artifacts", "Artifacts Collected", "Собранные артефакты")
	_add(&"run_summary_strongest", "Strongest Spell", "Сильнейшее заклинание")
	_add(&"run_summary_no_data", "No data", "Нет данных")
	_add(&"btn_restart_run", "✦  NEW RUN", "✦  НОВЫЙ ЗАБЕГ")
	_add(&"btn_main_menu", "✦  MAIN MENU", "✦  ГЛАВНОЕ МЕНЮ")

	_add(&"boss_incoming", "BOSS INCOMING!", "БОСС НАБЛИЖАЕТСЯ!")
	_add(&"boss_fight", "BOSS FIGHT", "БИТАВА С БОССОМ")
	_add(&"boss_name_volt_sentinel", "Volt Sentinel", "Страж Болтов")
	_add(&"boss_name_blast_architect", "Blast Architect", "Архитектор Взрывов")
	_add(&"boss_name_iron_titan", "Iron Titan", "Железный Титан")
	_add(&"boss_name_fury_monarch", "Fury Monarch", "Монарх Ярости")
	_add(&"boss_name_abyss_warden", "Abyss Warden", "Страж Бездны")
	_add(&"stat_max_hp", "Max HP", "Макс. ОЗ")
	_add(&"stat_hp_regen", "HP Regen", "Реген. ОЗ")
	_add(&"stat_dmg_reduction", "Dmg Reduction", "Сниж. урона")
	_add(&"stat_dodge", "Dodge", "Уклонение")
	_add(&"stat_speed", "Move Speed", "Скорость")
	_add(&"stat_crit_chance", "Crit Chance", "Шанс крита")
	_add(&"stat_crit_damage", "Crit Damage", "Сила крита")
	_add(&"stat_magic", "Magic Power", "Сила атаки")
	_add(&"stat_atk_mult", "Attack Mult", "Приумн. атаки")
	_add(&"stat_spell_duration", "Spell Duration", "Длит. заклинаний")
	_add(&"stat_area", "Spell Size", "Размер заклинаний")
	_add(&"stat_cd", "CD Reduction", "Перезарядка")
	_add(&"stat_proj_speed", "Proj Speed", "Скор. снарядов")
	_add(&"stat_enemy_hp", "Enemy Max HP", "Макс. HP врага")
	_add(&"stat_mana_gain", "XP Gain", "Получение опыта")
	_add(&"stat_pickup", "Pickup Range", "Радиус сбора")
	_add(&"stat_life_steal", "Life Steal", "Кража жизни")

	_add(&"hud_lv", "LV. ", "УР. ")

	_add(&"artifact_title", "✦  ARTIFACT  ✦", "✦  АРТЕФАКТ  ✦")
	_add(&"artifact_subtitle", "Claim your relic", "Забери свою реликвию")
	_add(&"artifacts_label", "Artifacts", "Артефакты")

	_add(&"inner_power_title", "✦  INNER POWER  ✦", "✦  ВНУТРЕННЯЯ СИЛА  ✦")
	_add(&"btn_inner_power", "✦  INNER POWER", "✦  ВНУТРЕННЯЯ СИЛА")
	_add(&"inner_power_subtitle", "Forge your inner strength", "Выкуй свою внутреннюю силу")
	_add(&"upgrade_max", "MAX", "МАКС")
	_add(&"vault_label", "Vault", "Хранилище")
	_add(&"earned_currency", "Earned:", "Заработано:")
	_add(&"currency", "Dust", "Пыль")
	_add(&"total_vault", "Vault:", "Хранилище:")
	_add(&"btn_reset_upgrades", "↺  RESET", "↺  СБРОС")
	_add(&"reset_confirm_title", "Reset all upgrades?", "Сбросить все улучшения?")
	_add(&"reset_confirm_desc", "All levels will be reset. Spent currency will be refunded.", "Все уровни будут сброшены. Потраченная валюта вернётся.")
	_add(&"btn_confirm_reset", "CONFIRM RESET", "ПОДТВЕРДИТЬ СБРОС")
	_add(&"btn_cancel_reset", "CANCEL", "ОТМЕНА")
	_add(&"reset_done", "Refunded: %d", "Возвращено: %d")

	_add(&"eff_dmg", "dmg", "урон")
	_add(&"eff_area", "area", "область")
	_add(&"eff_cast_speed", "cast speed", "скор. каста")
	_add(&"eff_proj_speed", "proj speed", "скор. снар.")
	_add(&"eff_projectile", "projectile", "снаряд")
	_add(&"eff_chain", "chain", "цепь")
	_add(&"eff_duration", "duration", "длительность")
	_add(&"eff_crit", "crit", "крит")
	_add(&"eff_speed", "speed", "скорость")
	_add(&"eff_hp", "HP", "ОЗ")
	_add(&"eff_pickup", "pickup", "сбор")
	_add(&"eff_xp", "XP", "опыт")
	_add(&"eff_lifesteal", "lifesteal", "кража HP")
	_add(&"eff_regen", "HP/s", "HP/с")
	_add(&"eff_dodge", "dodge", "уклонение")
	_add(&"eff_knockback", "knockback", "отброс")
	_add(&"eff_second_wind", "When HP < 25%: heal 50% over 3s (60s cd)", "При HP < 25%: лечение 50% за 3с (60с кд)")
	_add(&"eff_spell_echo", "Every 10th cast: spell duplicates", "Каждое 10-е заклинание: дублируется")
	_add(&"eff_tiny_menace", "25% smaller, +5% dodge", "На 25% меньше, +5% уворот")
	_add(&"eff_static_aura", "Enemies within 80 take 15% more damage", "Враги в радиусе 80 получают +15% урона")
	_add(&"eff_overflow", "25% of XP → temporary HP (decays 1/s)", "25% опыта → временные ОЗ (распад 1/с)")
	_add(&"eff_cascade", "Crits create shockwaves (50% dmg, 0.5s cd)", "Криты создают волну (50% урона, 0.5с кд)")

	# === COMMON (10) ===
	_add(&"art_grimoire_page", "Grimoire Page", "Страница гримуара")
	_add(&"art_desc_grimoire_page", "+10% damage to all spells", "+10% урон ко всем заклинаниям")
	_add(&"art_rune_of_haste", "Rune of Haste", "Руна стремительности")
	_add(&"art_desc_rune_of_haste", "+15% cooldown reduction", "+15% сокращение перезарядки")
	_add(&"art_lucky_coin", "Lucky Coin", "Счастливая монета")
	_add(&"art_desc_lucky_coin", "+20% XP gained from all sources", "+20% опыта из всех источников")
	_add(&"art_magnetic_core", "Magnetic Core", "Магнитное ядро")
	_add(&"art_desc_magnetic_core", "+50% pickup range", "+50% радиус сбора")
	_add(&"art_swift_boots", "Swift Boots", "Сапоги скорости")
	_add(&"art_desc_swift_boots", "+15% move speed", "+15% скорость передвижения")
	_add(&"art_iron_will", "Iron Will", "Железная воля")
	_add(&"art_desc_iron_will", "+5% dodge chance", "+5% шанс уворота")
	_add(&"art_vitality_dew", "Vitality Dew", "Роса жизненной силы")
	_add(&"art_desc_vitality_dew", "+10% max HP", "+10% макс. ОЗ")
	_add(&"art_quickdraw_charm", "Quickdraw Charm", "Амулет быстрой руки")
	_add(&"art_desc_quickdraw_charm", "+15% projectile speed", "+15% скорость снарядов")
	_add(&"art_mana_shard", "Mana Shard", "Осколок маны")
	_add(&"art_desc_mana_shard", "+10% cooldown reduction", "+10% сокращение перезарядки")
	_add(&"art_blood_gem", "Blood Gem", "Кровавый самоцвет")
	_add(&"art_desc_blood_gem", "+2% life steal", "+2% вампиризм")

	# === UNCOMMON (14) ===
	_add(&"art_ember_core", "Ember Core", "Огненное ядро")
	_add(&"art_desc_ember_core", "+25% fire damage, +15% fire area", "+25% огненный урон, +15% область огня")
	_add(&"art_arcane_crystal", "Arcane Crystal", "Тайный кристалл")
	_add(&"art_desc_arcane_crystal", "+20% arcane damage, +1 projectile", "+20% тайный урон, +1 снаряд")
	_add(&"art_storm_capacitor", "Storm Capacitor", "Штормовой конденсатор")
	_add(&"art_desc_storm_capacitor", "+1 chain jump for lightning", "+1 прыжок цепи для молний")
	_add(&"art_frost_shard", "Frost Shard", "Ледяной осколок")
	_add(&"art_desc_frost_shard", "+30% cold area, +20% duration", "+30% область холода, +20% длительность")
	_add(&"art_vitality_heart", "Vitality Heart", "Сердце жизни")
	_add(&"art_desc_vitality_heart", "+25% max HP, +0.5 HP/s regen", "+25% макс. ОЗ, +0.5 ОЗ/с реген.")
	_add(&"art_mana_crystal", "Mana Crystal", "Кристалл маны")
	_add(&"art_desc_mana_crystal", "-20% cooldown for all spells", "-20% перезарядка всех заклинаний")
	_add(&"art_rapid_quiver", "Rapid Quiver", "Скорый колчан")
	_add(&"art_desc_rapid_quiver", "+25% projectile speed for all", "+25% скорость снарядов всех заклинаний")
	_add(&"art_seeker_s_eye", "Seeker's Eye", "Око искателя")
	_add(&"art_desc_seeker_s_eye", "+30% pickup range, +10% XP", "+30% радиус сбора, +10% опыта")
	_add(&"art_battle_focus", "Battle Focus", "Боевой фокус")
	_add(&"art_desc_battle_focus", "+10% damage, +10% crit chance", "+10% урон, +10% шанс крита")
	_add(&"art_warden_s_oath", "Warden's Oath", "Клятва хранителя")
	_add(&"art_desc_warden_s_oath", "+15% max HP, +0.3 HP/s regen", "+15% макс. ОЗ, +0.3 ОЗ/с реген.")
	_add(&"art_flame_tongue", "Flame Tongue", "Пламенный язык")
	_add(&"art_desc_flame_tongue", "+20% fire damage, +1 projectile", "+20% огненный урон, +1 снаряд")
	_add(&"art_static_charge", "Static Charge", "Статический заряд")
	_add(&"art_desc_static_charge", "+15% lightning damage, +1 chain", "+15% урон молнией, +1 прыжок цепи")
	_add(&"art_blizzard_heart", "Blizzard Heart", "Сердце бури")
	_add(&"art_desc_blizzard_heart", "+25% cold damage, +15% cold area", "+25% урон холода, +15% область холода")
	_add(&"art_shadow_step", "Shadow Step", "Теневой шаг")
	_add(&"art_desc_shadow_step", "+10% move speed, +5% dodge", "+10% скорость, +5% уворот")

	# === RARE (16) ===
	_add(&"art_bloodstone", "Bloodstone", "Кровавый камень")
	_add(&"art_desc_bloodstone", "+25% crit chance, +10% damage", "+25% шанс крита, +10% урон")
	_add(&"art_ember_sigil", "Ember Sigil", "Печать углей")
	_add(&"art_desc_ember_sigil", "+30% fire damage, +25% fire area", "+30% огненный урон, +25% область огня")
	_add(&"art_storm_eye", "Storm Eye", "Око бури")
	_add(&"art_desc_storm_eye", "+20% lightning damage, +1 chain", "+20% урон молнией, +1 прыжок цепи")
	_add(&"art_frozen_heart", "Frozen Heart", "Ледяное сердце")
	_add(&"art_desc_frozen_heart", "+35% cold area, +20% cold duration", "+35% область холода, +20% длительность холода")
	_add(&"art_bouncing_essence", "Bouncing Essence", "Прыгучая эссенция")
	_add(&"art_desc_bouncing_essence", "+1 chain, +20% arcane duration", "+1 прыжок цепи, +20% длительность тайных")
	_add(&"art_glass_cannon", "Glass Cannon", "Стеклянная пушка")
	_add(&"art_desc_glass_cannon", "+50% damage to all spells", "+50% урон ко всем заклинаниям")
	_add(&"art_spectral_touch", "Spectral Touch", "Призрачное касание")
	_add(&"art_desc_spectral_touch", "3% life steal from all damage", "3% вампиризм от всего урона")
	_add(&"art_lethal_critical", "Lethal Critical", "Смертельный крит")
	_add(&"art_desc_lethal_critical", "+15% crit chance, +20% crit damage", "+15% шанс крита, +20% урон крита")
	_add(&"art_void_shard", "Void Shard", "Осколок пустоты")
	_add(&"art_desc_void_shard", "+10% all damage, +30% XP, +20% pickup", "+10% урон, +30% опыта, +20% сбор")
	_add(&"art_phoenix_feather", "Phoenix Feather", "Перо феникса")
	_add(&"art_desc_phoenix_feather", "+20% fire damage, +1 HP/s regen", "+20% огненный урон, +1 ОЗ/с реген.")
	_add(&"art_lightning_rod", "Lightning Rod", "Молниевой стержень")
	_add(&"art_desc_lightning_rod", "+25% lightning damage, +2 chains", "+25% урон молнией, +2 прыжка цепи")
	_add(&"art_permafrost_core", "Permafrost Core", "Ядро вечной мерзлоты")
	_add(&"art_desc_permafrost_core", "+30% cold damage, +25% cold duration", "+30% урон холода, +25% длительность холода")
	_add(&"art_arcane_focus", "Arcane Focus", "Тайный фокус")
	_add(&"art_desc_arcane_focus", "+25% arcane damage, +1 projectile", "+25% тайный урон, +1 снаряд")
	_add(&"art_berserker_s_mark", "Berserker's Mark", "Знак берсерка")
	_add(&"art_desc_berserker_s_mark", "+30% damage, +15% move speed", "+30% урон, +15% скорость")
	_add(&"art_sage_s_wisdom", "Sage's Wisdom", "Мудрость мудреца")
	_add(&"art_desc_sage_s_wisdom", "+25% XP, -20% cooldown", "+25% опыта, -20% перезарядка")
	_add(&"art_vampiric_fang", "Vampiric Fang", "Вампирский клык")
	_add(&"art_desc_vampiric_fang", "+5% life steal, +15% damage", "+5% вампиризм, +15% урон")

	# === LEGENDARY (10) ===
	_add(&"art_cursed_phylactery", "Cursed Phylactery", "Проклятая филактерия")
	_add(&"art_desc_cursed_phylactery", "×2 damage to all spells", "×2 урон ко всем заклинаниям")
	_add(&"art_celestial_orb", "Celestial Orb", "Небесная сфера")
	_add(&"art_desc_celestial_orb", "+30% all damage, +10% move speed", "+30% урон, +10% скорость")
	_add(&"art_soul_harvest", "Soul Harvest", "Жатва душ")
	_add(&"art_desc_soul_harvest", "+0.1 HP/s regen, +1 HP per enemy killed", "+0.1 ОЗ/с реген., +1 ОЗ за врага")
	_add(&"art_dragon_s_heart", "Dragon's Heart", "Сердце дракона")
	_add(&"art_desc_dragon_s_heart", "+40% fire damage, +30% fire area", "+40% огненный урон, +30% область огня")
	_add(&"art_tempest_crown", "Tempest Crown", "Корона бури")
	_add(&"art_desc_tempest_crown", "+30% lightning damage, +3 chains", "+30% урон молнией, +3 прыжка цепи")
	_add(&"art_glacial_spire", "Glacial Spire", "Ледяной шпиль")
	_add(&"art_desc_glacial_spire", "+40% cold damage, +30% cold duration", "+40% урон холода, +30% длительность холода")
	_add(&"art_void_amulet", "Void Amulet", "Амулет пустоты")
	_add(&"art_desc_void_amulet", "+25% all damage, +2 projectiles, +15% XP", "+25% урон, +2 снаряда, +15% опыта")
	_add(&"art_blood_crown", "Blood Crown", "Кровавая корона")
	_add(&"art_desc_blood_crown", "+40% damage, +10% life steal", "+40% урон, +10% вампиризм")
	_add(&"art_chrono_shard", "Chrono Shard", "Осколок времени")
	_add(&"art_desc_chrono_shard", "-30% cooldown, +25% projectile speed", "-30% перезарядка, +25% скорость снарядов")
	_add(&"art_infinity_flame", "Infinity Flame", "Пламя бесконечности")
	_add(&"art_desc_infinity_flame", "+35% fire damage, +30% area, +1 projectile", "+35% огненный урон, +30% область, +1 снаряд")

	_add(&"art_second_wind", "Second Wind", "Второе дыхание")
	_add(&"art_desc_second_wind", "When HP < 25%: heal 50% over 3s (60s cd)", "При HP < 25%: лечение 50% за 3с (60с кд)")
	_add(&"art_tiny_menace", "Tiny Menace", "Крошечная угроза")
	_add(&"art_desc_tiny_menace", "25% smaller, +5% dodge chance", "На 25% меньше, +5% шанс уворота")
	_add(&"art_spell_echo", "Spell Echo", "Эхо заклинаний")
	_add(&"art_desc_spell_echo", "+20% damage, every 10th cast duplicates", "+20% урон, каждое 10-е заклинание дублируется")
	_add(&"art_static_aura", "Static Aura", "Статическая аура")
	_add(&"art_desc_static_aura", "Enemies within 80 take periodic damage (5 dmg/s)", "Враги в радиусе 80 получают периодический урон (5 урон/с)")
	_add(&"art_overflow", "Overflow", "Переполнение")
	_add(&"art_desc_overflow", "25% of XP gained as temporary HP (decays 1/s)", "25% опыта → временные ОЗ (распад 1/с)")
	_add(&"art_cascade", "Cascade", "Каскад")
	_add(&"art_desc_cascade", "Critical hits create shockwaves (50% dmg, 100 radius, 0.5s cd)", "Криты создают ударные волны (50% урона, 100 ед., 0.5с кд)")

	_add(&"art_explosive_tip", "Explosive Tip", "Взрывной наконечник")
	_add(&"art_desc_explosive_tip", "Killed enemies explode dealing AoE damage (15 dmg)", "Убитые враги взрываются, нанося AoE урон (15 урон)")
	_add(&"art_phantom_speed", "Phantom Speed", "Призрачная скорость")
	_add(&"art_desc_phantom_speed", "Moving leaves a damage trail (5 dmg/sec)", "Движение оставляет след урона (5 урон/сек)")
	_add(&"art_arcane_storm", "Arcane Storm", "Тайный шторм")
	_add(&"art_desc_arcane_storm", "Periodic AoE damage around player (8 dmg/sec)", "Периодический урон по области (8 урон/сек)")
	_add(&"art_spell_weaver", "Spell Weaver", "Ткач заклинаний")
	_add(&"art_desc_spell_weaver", "Every 3rd spell cast fires 2 copies", "Каждое 3-е заклинание выпускает 2 копии")

	# === NEW ARTIFACTS: POISON (4) ===
	_add(&"art_plague_sigil", "Plague Sigil", "Печать чумы")
	_add(&"art_desc_plague_sigil", "+30% poison damage, poison zones tick 25% faster", "+30% урон яда, ядовитые зоны тикают на 25% чаще")
	_add(&"art_venom_codex", "Venom Codex", "Ядовитый кодекс")
	_add(&"art_desc_venom_codex", "+40% poison damage, +35% poison area, -10% move speed", "+40% урон яда, +35% область яда, -10% скорость")
	_add(&"art_toxic_bloom", "Toxic Bloom", "Токсичный цветок")
	_add(&"art_desc_toxic_bloom", "On kill: 20% chance to create small poison zone (2s)", "При убийстве: 20% шанс создать малую ядовитую зону (2с)")
	_add(&"art_miasma_flask", "Miasma Flask", "Фляга миазмов")
	_add(&"art_desc_miasma_flask", "+50% poison duration, poison slows enemies 20%", "+50% длительность яда, яд замедляет врагов на 20%")

	# === NEW ARTIFACTS: SPIRIT (4) ===
	_add(&"art_soul_lantern", "Soul Lantern", "Фонарь душ")
	_add(&"art_desc_soul_lantern", "+30% spirit damage, spirit projectiles leave damage trails (1s)", "+30% урон духа, духи оставляют следы урона (1с)")
	_add(&"art_wraith_mantle", "Wraith Mantle", "Плащ призрака")
	_add(&"art_desc_wraith_mantle", "+25% spirit damage, +20% projectile speed, +1 spirit projectile", "+25% урон духа, +20% скорость снарядов, +1 дух")
	_add(&"art_phantom_seal", "Phantom Seal", "Печать призрака")
	_add(&"art_desc_phantom_seal", "Spirit projectiles crit on first hit, +10% global crit", "Духи критят при первом ударе, +10% глобальный крит")
	_add(&"art_haunt_essence", "Haunt Essence", "Эссенция проклятия")
	_add(&"art_desc_haunt_essence", "+40% spirit damage vs bosses, +0.1 HP per spirit kill", "+40% урон духа по боссам, +0.1 ОЗ за убийство духом")

	# === NEW ARTIFACTS: PHYSICAL (3) ===
	_add(&"art_whetstone", "Whetstone", "Точильный камень")
	_add(&"art_desc_whetstone", "+15% physical spell damage", "+15% урон физических заклинаний")
	_add(&"art_blade_rune", "Blade Rune", "Руна клинка")
	_add(&"art_desc_blade_rune", "+25% physical damage, +1 pierce", "+25% урон физических, +1 пробитие")
	_add(&"art_executioner_s_brand", "Executioner's Brand", "Клеймо палача")
	_add(&"art_desc_executioner_s_brand", "+50% damage to enemies below 30% HP", "+50% урон по врагам с HP < 30%")

	# === NEW ARTIFACTS: GLOBAL (10) ===
	_add(&"art_orbweaver_s_thread", "Orbweaver's Thread", "Нить орбиты")
	_add(&"art_desc_orbweaver_s_thread", "+20% orbit speed (Orbiting Arcana)", "+20% скорость орбит")
	_add(&"art_clockwork_cog", "Clockwork Cog", "Шестерёнка")
	_add(&"art_desc_clockwork_cog", "-10% cooldown, every 100 kills: -5% more (max -25%)", "-10% перезарядка, каждые 100 убийств: -5% ещё (макс -25%)")
	_add(&"art_focus_gem", "Focus Gem", "Камень фокуса")
	_add(&"art_desc_focus_gem", "+20% damage to single-target spells", "+20% урон заклинаниям с одной целью")
	_add(&"art_scholar_s_monocle", "Scholar's Monocle", "Монокль учёного")
	_add(&"art_desc_scholar_s_monocle", "+30% XP, every 5 levels: +5% all damage", "+30% опыта, каждые 5 уровней: +5% урон всем")
	_add(&"art_echo_sigil", "Echo Sigil", "Печать эха")
	_add(&"art_desc_echo_sigil", "+15% AoE radius for all spells", "+15% радиус AoE всех заклинаний")
	_add(&"art_wind_totem", "Wind Totem", "Тотем ветра")
	_add(&"art_desc_wind_totem", "+20% move speed, +10% projectile speed", "+20% скорость передвижения, +10% скорость снарядов")
	_add(&"art_death_bell", "Death Bell", "Колокол смерти")
	_add(&"art_desc_death_bell", "+0.3 HP per enemy killed", "+0.3 ОЗ за убитого врага")
	_add(&"art_iron_aegis", "Iron Aegis", "Железный aegis")
	_add(&"art_desc_iron_aegis", "+10% dodge, +20% max HP", "+10% уклонение, +20% макс. ОЗ")
	_add(&"art_abyssal_lens", "Abyssal Lens", "Бездонная линза")
	_add(&"art_desc_abyssal_lens", "+20% boss damage, +10% projectile speed", "+20% урон боссам, +10% скорость снарядов")
	_add(&"art_arcane_amplifier", "Arcane Amplifier", "Тайный усилитель")
	_add(&"art_desc_arcane_amplifier", "+15% arcane damage, +1 arcane projectile", "+15% тайный урон, +1 снаряд")

	# === NEW ARTIFACTS: ELEMENT (3) ===
	_add(&"art_glacial_core", "Glacial Core", "Ледяное ядро")
	_add(&"art_desc_glacial_core", "+40% cold duration, +20% cold damage, -10% move speed", "+40% длительность холода, +20% урон холода, -10% скорость")
	_add(&"art_conductor_s_rod", "Conductor's Rod", "Стержень проводника")
	_add(&"art_desc_conductor_s_rod", "+30% lightning damage, lightning always chains 1 time", "+30% урон молнией, молния всегда передаётся 1 раз")
	_add(&"art_volcanic_glyph", "Volcanic Glyph", "Вулканический glyph")
	_add(&"art_desc_volcanic_glyph", "+20% fire damage, fire kills leave burning trail", "+20% огненный урон, убийства огнём оставляют горящий след")

	# === NEW ARTIFACTS: RISKY (5) ===
	_add(&"art_martyr_s_brand", "Martyr's Brand", "Клеймо мученика")
	_add(&"art_desc_martyr_s_brand", "+1% damage per 1% missing HP, -20% max HP", "+1% урон за каждый % потерянного HP, -20% макс. ОЗ")
	_add(&"art_twin_cast", "Twin Cast", "Двойной каст")
	_add(&"art_desc_twin_cast", "20% chance to cast spell twice, +25% cooldown", "20% шанс каста дважды, +25% перезарядка")
	_add(&"art_berserker_s_oath", "Berserker's Oath", "Клятва берсерка")
	_add(&"art_desc_berserker_s_oath", "x1.5 damage, regen disabled, life steal x2", "x1.5 урон, реген отключен, вампиризм x2")
	_add(&"art_arcane_overload", "Arcane Overload", "Перегрузка магии")
	_add(&"art_desc_arcane_overload", "+40% arcane damage", "+40% тайный урон")
	_add(&"art_gambler_s_dice", "Gambler's Dice", "Кости игрока")
	_add(&"art_desc_gambler_s_dice", "Every 30s: random x0.5 or x2 damage for 5s", "Каждые 30с: случайно x0.5 или x2 урон на 5с")

	# === NEW ARTIFACTS: LEGENDARY (3) ===
	_add(&"art_void_codex", "Void Codex", "Кодекс пустоты")
	_add(&"art_desc_void_codex", "+20% all damage, every 5th shot auto-crits", "+20% урон, каждое 5-е попадание крит")
	_add(&"art_inferno_grimoire", "Inferno Grimoire", "Гrimуар инферно")
	_add(&"art_desc_inferno_grimoire", "+35% fire, poison, lightning damage", "+35% урон огня, яда, молнии")
	_add(&"art_absolute_zero", "Absolute Zero", "Абсолютный ноль")
	_add(&"art_desc_absolute_zero", "+60% cold damage, +50% cold area", "+60% урон холода, +50% область холода")

	# === NEW ARTIFACTS: FUSION (3) ===
	_add(&"art_firenado_lens", "Firenado Lens", "Линза Огненного вихря")
	_add(&"art_desc_firenado_lens", "Firenado: +40% damage, +25% area", "Огненный вихрь: +40% урон, +25% область")
	_add(&"art_thunderbolt_coil", "Thunderbolt Coil", "Катушка молнии")
	_add(&"art_desc_thunderbolt_coil", "Thunderbolt: +2 chain jumps, +30% damage", "Thunderbolt: +2 прыжка цепи, +30% урон")
	_add(&"art_crystal_aegis_shard", "Crystal Aegis Shard", "Осколок Кристального aegis")
	_add(&"art_desc_crystal_aegis_shard", "Crystal Aegis: +40% shield absorb", "Кристальный aegis: +40% поглощение")

	_add(&"eff_move_trail", "damage trail (5/s)", "след урона (5/с)")
	_add(&"eff_low_hp_explode", "death explosion", "взрыв при смерти")
	_add(&"eff_spell_split", "spell split", "разделение заклинания")
	_add(&"eff_damage_aura", "damage aura (8/s)", "аура урона (8/с)")
	_add(&"eff_boss_dmg", "boss dmg", "урон боссам")
	_add(&"eff_onkill_regen", "HP/kill", "HP/убийство")
	_add(&"eff_pierce", "pierce", "пробитие")
	_add(&"eff_twin_cast", "20% double cast", "20% двойной каст")
	_add(&"eff_berserker_oath", "No regen, x1.5 dmg", "Без регена, x1.5 урон")
	_add(&"eff_gambler_dice", "Random x0.5/x2 every 30s", "Случайно x0.5/x2 каждые 30с")
	_add(&"eff_toxic_bloom", "Kill → poison zone", "Убийство → ядовитая зона")
	_add(&"eff_volcanic_glyph", "Kill → fire trail", "Убийство → огненный след")

	_add(&"rarity_common", "COMMON", "ОБЫЧНЫЙ")
	_add(&"rarity_uncommon", "UNCOMMON", "НЕОБЫЧНЫЙ")
	_add(&"rarity_rare", "RARE", "РЕДКИЙ")
	_add(&"rarity_legendary", "LEGENDARY", "ЛЕГЕНДАРНЫЙ")

	_add(&"mod_homing", "Homing", "Самонаведение")
	_add(&"mod_chain_lightning", "Chain Lightning", "Цепная молния")
	_add(&"mod_chain_field", "Chain Field", "Цепное поле")
	_add(&"mod_explode", "Explosion", "Взрыв")
	_add(&"mod_split_fireball", "Split Fireball", "Раскол огня")
	_add(&"mod_mega_explosion", "Mega Explosion", "Мегавзрыв")
	_add(&"mod_piercing_blaze", "Piercing Blaze", "Пронзающий огонь")
	_add(&"mod_wide_orbit", "Pulsating Vortex", "Пульсирующий вихрь")
	_add(&"mod_acceleration", "Blade Strike", "Удар клинка")
	_add(&"mod_multiplicity", "Cross Storm", "Перекрёстный шторм")
	_add(&"mod_chain_amplifier", "Chain Amplifier", "Цепной усилитель")
	_add(&"mod_overcharge", "Overcharge", "Перегрузка")
	_add(&"mod_thunderstorm", "Thunderstorm", "Грозовой шторм")
	_add(&"mod_tornado", "Gravity Well", "Гравитационный колодец")
	_add(&"mod_gale_force", "Seeking Wind", "Ищущий ветер")
	_add(&"mod_tempest", "Tempest", "Буря")
	_add(&"mod_prism", "Spinning Prism", "Вращающаяся призма")
	_add(&"mod_photon", "Photon", "Фотон")
	_add(&"mod_refraction", "Refraction", "Преломление")
	_add(&"mod_refraction_shield_mod", "Refraction Shield", "Преломляющий щит")
	_add(&"mod_thunderfield", "Shockwave", "Ударная волна")
	_add(&"mod_arc_flash", "Arc Flash", "Дуговая вспышка")
	_add(&"mod_phantom", "Phantom Legion", "Фантомный легион")
	_add(&"mod_phantom_blades", "Phantom Blades", "Фантомные клинки")
	_add(&"mod_wraith", "Spectral Pierce", "Призрачный прокол")
	_add(&"mod_haunt", "Haunt", "Наваждение")
	_add(&"mod_fortress", "Thorns", "Шипы")
	_add(&"mod_aegis", "Aegis", "Эгида")
	_add(&"mod_dragon_breath", "Dragon Breath", "Драконье дыхание")
	_add(&"mod_fire_fan", "Fire Fan", "Огненный веер")
	_add(&"mod_burning_ash", "Burning Ash", "Жгучий пепел")
	_add(&"mod_dragon_needle", "Dragon Needle", "Драконья игла")
	_add(&"mod_needle_fan", "Needle Fan", "Веер игл")
	_add(&"mod_frost_shard", "Frost Shard", "Ледяной осколок")
	_add(&"mod_needle_volley", "Needle Volley", "Веер игл")
	_add(&"mod_ricochet_needle", "Ricochet Needle", "Рикошетная игла")
	_add(&"mod_magic_missile_storm", "Missile Storm", "Шторм ракет")

	_add(&"mod_desc_homing", "Bolts curve toward the nearest enemy, never missing — but hit 20% softer", "Снаряды искривляются к ближайшему врагу, никогда не промахиваясь — но бьют на 20% слабее")
	_add(&"mod_desc_chain_lightning", "Each hit arcs to a nearby foe at 50% power — 10% weaker main hit", "Каждый удар перепрыгивает на ближнего врага на 50% силы — основной удар на 10% слабее")
	_add(&"mod_desc_explode", "Bolts detonate in a blast radius at half power on impact — 30% weaker bolt", "Снаряды взрываются по области с половинной силой при попадании — снаряд на 30% слабее")
	_add(&"mod_desc_split_fireball", "Fireball shatters into 3 smaller projectiles on detonation — each hits 30% softer", "Огненный шар раскалывается на 3 малых снаряда при взрыве — каждый на 30% слабее")
	_add(&"mod_desc_fireball_meteor", "Calls down a massive meteor — 180% slower, 100% more damage, 300% larger blast", "Вызывает массивный метеор — на 180% медленнее, +100% урона, радиус взрыва ×4.0")
	_add(&"mod_desc_mega_explosion", "Explosion swells to enormous size — 15% weaker hit but the blast is inescapable", "Взрыв разрастается до огромных размеров — удар на 15% слабее, но взрыв не избежать")
	_add(&"mod_desc_piercing_blaze", "Fireball pierces 4 extra enemies before detonating, plus 10% more damage", "Огненный шар пробивает 4 дополнительных врага перед взрывом, плюс 10% урона")
	_add(&"mod_desc_wide_orbit", "Orbit breathes in and out, swelling and contracting — 15% less damage per blade", "Орбита дышит — расширяется и сжимается — на 15% меньше урона за клинок")
	_add(&"mod_desc_acceleration", "Blades aggressively fly out to slash nearby enemies and return — 10% less damage each", "Клинки агрессивно вылетают к врагам, разят и возвращаются — на 10% меньше урона каждый")
	_add(&"mod_desc_multiplicity", "4 additional blades in a counter-rotating ring — 25% less damage per blade", "4 доп. клинка во встречном вращении — на 25% меньше урона за клинок")
	_add(&"mod_desc_chain_amplifier", "Chains strike 4 extra targets with longer reach at 60% power — 20% weaker main bolt", "Цепи бьют 4 доп. цели дальше на 60% силы — основной удар на 20% слабее")
	_add(&"mod_desc_overcharge", "A single devastating bolt at 2.5x damage, but chains are lost entirely", "Единый сокрушительный удар в 2.5x урон, но цепи полностью теряются")
	_add(&"mod_desc_thunderstorm", "Each strike triggers an AoE burst at 40% power — 20% weaker main hit, chains remain", "Каждый удар вызывает AoE взрыв на 40% силы — основной удар на 20% слабее, цепи остаются")
	_add(&"mod_desc_tornado", "Vortex becomes a gravity well with 5x pull strength, no damage", "Вихрь становится гравитационным колодцем с 5x силой притяжения, без урона")
	_add(&"mod_desc_gale_force", "Vortex chases enemies at +40% speed, -15% damage", "Вихрь преследует врагов на +40% быстрее, -15% урона")
	_add(&"mod_desc_tempest", "Paired vortexes rotating around shared axis, 2.5x area, 1.5x damage", "Парные вихри вокруг общей оси, 2.5x область, 1.5x урон")
	_add(&"mod_desc_prism", "5 rays in a 90° fan, whole structure rotates — each deals 40% less damage", "5 лучей веером 90°, вся конструкция вращается — каждый на 40% слабее")
	_add(&"mod_desc_photon", "2.5-fold damage but fires as a pulse every 1.5s", "2.5x урон, но стреляет импульсом каждые 1.5с")
	_add(&"mod_desc_refraction", "Ray bounces off screen edges up to 2 times — 15% softer per bounce", "Луч отражается от краёв экрана до 2 раз — на 15% слабее за отскок")
	_add(&"mod_desc_thunderfield", "Zone emits expanding shockwave rings every 3s that push enemies back — 30% less tick damage", "Зона излучает кольца ударной волны каждые 3с, отталкивая врагов — на 30% меньше урона за тик")
	_add(&"mod_desc_arc_flash", "Tick rate triples with frantic arcs — 50% less damage but relentless pressure", "Скорость тиков утраивается — на 50% меньше урона, но безжалостное давление")
	_add(&"mod_desc_chain_field", "Each tick arcs outside the zone to 3 nearby enemies at 50% power", "Каждый тик перепрыгивает за зону к 3 ближним врагам на 50% силы")
	_add(&"mod_desc_phantom", "3 additional spirits, each targets a different enemy independently — 30% less damage each", "3 дополнительных духа, каждый целит в отдельного врага — на 30% меньше урона каждый")
	_add(&"mod_desc_phantom_blades", "Spirits deal instant damage at the target instead of firing bolts — 15% less damage", "Духи наносят мгновенный урон цели вместо выстрела снарядом — на 15% меньше урона")
	_add(&"mod_desc_wraith", "Bolts pierce through enemies with an ethereal trail, travelling much further — 15% less damage", "Снаряды пронзают врагов с призрачным следом, летят намного дальше — на 15% меньше урона")
	_add(&"mod_desc_haunt", "Spirits fly to enemies and explode for 150% damage AoE, then recover for 2s", "Духи летят к врагам и взрываются на 150% урона по области, затем восстанавливаются 2с")
	_add(&"mod_desc_fortress", "On absorb: deal 15 base damage to all enemies in range 100 — +20% cooldown", "При поглощении: 15 базового урона всем врагам в радиусе 100 — +20% перезарядки")
	_add(&"mod_desc_refraction_shield_mod", "Absorbing a hit launches 6 homing arcane projectiles — 10 base damage each", "Поглощение удара запускает 6 самонаводящихся тайных снарядов — 10 базового урона каждый")
	_add(&"mod_desc_aegis", "1 charge that fully absorbs all damage, -60% cooldown", "1 заряд, полностью поглощающий любой урон, -60% перезарядки")
	_add(&"mod_desc_dragon_breath", "Narrow concentrated beam with +150% range and +50% damage", "Узкий сконцентрированный луч с +150% дальности и +50% урона")
	_add(&"mod_desc_fire_fan", "Flame splits into 3 cones in a 120° fan — each 20% weaker but triple coverage", "Пламя разветвляется на 3 конуса веером 120° — каждый на 20% слабее, но тройное покрытие")
	_add(&"mod_desc_burning_ash", "Enemies burn for 30% more damage over 2s after leaving the cone — 25% less base power but lingering flames", "Враги горят на 30% больше урона 2с после выхода из конуса — на 25% меньше базы, но тлеющее пламя")
	_add(&"mod_desc_dragon_needle", "Cone doubles in width and reach — a torrent of needles, but 40% slower burn rate", "Конус вдвое шире и дальше — поток игл, но скорость горения на 40% медленнее")
	_add(&"mod_desc_needle_fan", "Needles split into 3 cones fanning outward — each 20% weaker but triple coverage", "Иглы разветвляются на 3 конуса веером — каждый на 20% слабее, но тройное покрытие")
	_add(&"mod_desc_frost_shard", "Icy needles radiate in all directions, freezing enemies solid for 2 seconds with a 2-second thaw — 25% less damage but 360° coverage and chill", "Ледяные иглы расходятся во все стороны, замораживая врагов намертво на 2 секунды с оттаиванием за 2 секунды — на 25% меньше урона, но покрытие 360° и мороз")
	_add(&"mod_desc_needle_volley", "7 needles in a 45° cone burst — +30% cooldown", "7 игл конусом 45° — перезарядка +30%")
	_add(&"mod_desc_ricochet_needle", "Needles bounce off screen edges up to 3 times, 2 mini-needles per bounce — -15% damage", "Иглы рикошетят от краёв экрана до 3 раз, 2 мини-иглы за отскок — -15% урона")
	_add(&"mod_desc_magic_missile_storm", "Fires 5 bolts per cast in a wide spread — each 40% weaker but overwhelming volume", "Выпускает 5 снарядов широким веером — каждый на 40% слабее, но подавляющий объём")

	_add(&"mod_toxic_bloom", "Toxic Bloom", "Токсичный расцвет")
	_add(&"mod_miasma", "Miasma", "Миазм")
	_add(&"mod_plague", "Plague", "Мор")
	_add(&"mod_desc_toxic_bloom", "Enemies killed in the pool explode for 50% damage AoE — pools spread poison on death", "Враги, убитые в луже, взрываются на 50% урона по области — лужи распространяют яд при гибели")
	_add(&"mod_desc_miasma", "2.5x pool radius, −40% damage per tick — vast but weak", "Радиус лужи ×2.5, −40% урона за тик — обширно, но слабо")
	_add(&"mod_desc_plague", "3x tick speed, −25% damage each — rapid poison", "Скорость тиков ×3, −25% урона за тик — стремительный яд")

	_add(&"mod_ice_shards", "Ice Shards", "Ледяные осколки")
	_add(&"mod_permafrost", "Permafrost", "Вечная мерзлота")
	_add(&"mod_crystallize", "Crystallize", "Кристаллизация")
	_add(&"mod_desc_ice_shards", "Shatter sends 5 ice shards dealing 30% damage each", "Разлом отправляет 5 ледяных осколков, каждый наносит 30% урона")
	_add(&"mod_desc_permafrost", "Frozen enemies take +20% damage from all sources for 3s", "Замороженные враги получают +20% урон от всех источников 3с")
	_add(&"mod_desc_crystallize", "Frozen enemies explode on death, dealing area damage", "Замороженные враги взрываются при смерти, нанося урон по области")

	_add(&"mod_title", "◈  TRANSMUTE  ◈", "◈  ТРАНСМУТАЦИЯ  ◈")
	_add(&"mod_subtitle", "Choose evolution for %s", "Выбери эволюцию для %s")
	_add(&"mod_fusion_hint_title", "Possible fusions:", "Возможные фьюжны:")
	_add(&"mod_fusion_locked", "locked", "нужен")
	_add(&"card_epic_mod", "★★★ Epic Mod", "★★★ Эпик Мод")
	_add(&"card_new_spell", "★★ New Spell", "★★ Новое закл.")
	_add(&"card_stat_boost", "★ Stat Boost", "★ Улучш. стат.")
	_add(&"card_fusion", "◈◈◈ Fusion", "◈◈◈ Слияние")

	_add(&"spell_INFERNO_NOVA", "Inferno Nova", "Инферно Нова")
	_add(&"spell_THUNDERBOLT", "Thunderbolt", "Громовая Стрела")
	_add(&"spell_ASTRAL_SWARM", "Astral Swarm", "Астральный Рой")
	_add(&"spell_FIRENADO", "Firenado", "Огненный Торнадо")
	_add(&"spell_TOXIC_NEEDLES", "Toxic Needles", "Токсичные Иглы")

	_add(&"spell_ARCANE_PRISON", "Arcane Prison", "Тайная Тюрьма")
	_add(&"spell_PHOTON_STORM", "Photon Storm", "Фотонная Буря")
	_add(&"spell_PHASE_BOLT", "Phase Bolt", "Фазовый Снаряд")
	_add(&"spell_GALVANIC_CHAIN", "Galvanic Chain", "Гальваническая Цепь")
	_add(&"spell_ARC_OVERLOAD", "Arc Overload", "Дуговая Перегрузка")
	_add(&"spell_SEISMIC_PULSE", "Seismic Pulse", "Сейсмический Импульс")
	_add(&"spell_PHANTOM_ORBIT", "Phantom Orbit", "Призрачная Орбита")
	_add(&"spell_SOUL_BURST", "Soul Burst", "Взрыв Души")
	_add(&"spell_BLADE_VORTEX", "Blade Vortex", "Клинковый Вихрь")
	_add(&"spell_CRYSTAL_AEGIS", "Crystal Aegis", "Кристальный Эгида")
	_add(&"spell_FLAME_WARD", "Flame Ward", "Пламенная Охрана")
	_add(&"spell_MIRROR_SHARDS", "Mirror Shards", "Зеркальные Осколки")
	_add(&"spell_FROST_LANCE", "Frost Lance", "Ледяное Копьё")
	_add(&"spell_TOXIC_BLOOM", "Toxic Bloom", "Токсичный Цветок")

	_add(&"spell_magic_bolt", "Magic Bolt", "Маг. снаряд")
	_add(&"spell_fireball", "Fireball", "Огненный шар")
	_add(&"spell_orbiting_arcana", "Orbiting Arcana", "Орбит. аркана")
	_add(&"spell_lightning_strike", "Lightning Strike", "Молния")
	_add(&"spell_cyclone", "Cyclone", "Циклон")
	_add(&"spell_arcane_ray", "Arcane Ray", "Тайный луч")
	_add(&"spell_electric_zone", "Electric Zone", "Электр. зона")
	_add(&"spell_spirit", "Spirit", "Дух")
	_add(&"spell_shield", "Shield", "Щит")
	_add(&"spell_fire_breath", "Fire Breath", "Огненное дыхание")
	_add(&"spell_needle", "Needle", "Игла")
	_add(&"spell_poison_pool", "Poison Pool", "Ядовитая лужа")
	_add(&"spell_frost_nova", "Frost Nova", "Морозная волна")
	_add(&"new_spell", "New Spell", "Новое заклинание")
	_add(&"upgrade_spell", "Upgrade %s", "Улучшить %s")

	_add(&"mod_fireball_split", "Split Fireball", "Раскалённый огненный шар")
	_add(&"mod_fireball_meteor", "Skyfall", "Небесный удар")
	_add(&"mod_fireball_pierce", "Piercing Blaze", "Пронзающее пламя")
	_add(&"mod_magic_bolt_storm", "Magic Missile Storm", "Шторм магических снарядов")
	_add(&"mod_magic_bolt_homing", "Homing", "Самонаведение")
	_add(&"mod_magic_bolt_chain", "Chain Lightning", "Цепная молния")
	_add(&"mod_orbiting_arcana_vortex", "Pulsating Vortex", "Пульсирующий вихрь")
	_add(&"mod_orbiting_arcana_blade", "Blade Strike", "Удар клинка")
	_add(&"mod_orbiting_arcana_cross", "Cross Storm", "Крестовый шторм")
	_add(&"mod_lightning_strike_chain", "Chain Amplifier", "Усилитель цепи")
	_add(&"mod_lightning_strike_overcharge", "Overcharge", "Перегрузка")
	_add(&"mod_lightning_strike_rapid", "Rapid Bolt", "Быстрая стрела")
	_add(&"mod_cyclone_gravity", "Gravity Well", "Гравитационная яма")
	_add(&"mod_cyclone_gale", "Seeking Wind", "Ветер преследования")
	_add(&"mod_cyclone_twin", "Twin Cyclone", "Двойной циклон")
	_add(&"mod_arcane_ray_prism", "Spinning Prism", "Вращающаяся призма")
	_add(&"mod_arcane_ray_photon", "Photon", "Фотон")
	_add(&"mod_arcane_ray_refraction", "Refraction", "Преломление")
	_add(&"mod_electric_zone_shockwave", "Shockwave", "Ударная волна")
	_add(&"mod_electric_zone_arc", "Arc Flash", "Вспышка дуги")
	_add(&"mod_electric_zone_chain", "Chain Lightning", "Цепная молния")
	_add(&"mod_spirit_phantom", "Phantom Legion", "Призрачный легион")
	_add(&"mod_spirit_blades", "Phantom Blades", "Призрачные клинки")
	_add(&"mod_spirit_haunt", "Haunt", "Наваждение")
	_add(&"mod_shield_thorns", "Thorns", "Шипы")
	_add(&"mod_shield_refraction", "Refraction", "Преломление")
	_add(&"mod_shield_aegis", "Aegis", "Эгида")
	_add(&"mod_fire_breath_dragon", "Dragon Breath", "Драконье дыхание")
	_add(&"mod_fire_breath_fan", "Fire Fan", "Огненный веер")
	_add(&"mod_fire_breath_ash", "Burning Ash", "Горящий пепел")
	_add(&"mod_needle_volley", "Needle Volley", "Залп игл")
	_add(&"mod_needle_ricochet", "Ricochet Needle", "Рикошетная игла")
	_add(&"mod_needle_frost", "Frost Shard", "Ледяной осколок")
	_add(&"mod_poison_pool_bloom", "Toxic Bloom", "Токсичный цветок")
	_add(&"mod_poison_pool_miasma", "Miasma", "Миазм")
	_add(&"mod_poison_pool_plague", "Plague", "Чума")
	_add(&"mod_frost_nova_shards", "Ice Shards", "Ледяные осколки")
	_add(&"mod_frost_nova_permafrost", "Permafrost", "Мерзлота")
	_add(&"mod_frost_nova_crystallize", "Crystallize", "Кристаллизация")

	_add(&"mb_lv1", "Fires homing bolts at the nearest enemy", "Выпускает самонаводящиеся снаряды в ближайшего врага")
	_add(&"mb_lv2", "Damage up 25%, cooldown down 8%", "Урон +25%, перезарядка -8%")
	_add(&"mb_lv3", "Damage up 55%, cooldown down 15%, speed up 15%", "Урон +55%, перезарядка -15%, скорость +15%")
	_add(&"mb_lv4", "Damage up 90%, cooldown down 22%, pierces 1 more", "Урон +90%, перезарядка -22%, пробивает ещё 1")
	_add(&"mb_lv5", "Damage up 140%, cooldown down 30%, pierces 2 more, +1 projectile", "Урон +140%, перезарядка -30%, пробивает ещё 2, +1 снаряд")

	_add(&"fb_lv1", "Launches an explosive fireball that detonates on contact", "Запускает взрывной огненный шар, детонирующий при контакте")
	_add(&"fb_lv2", "Damage up 30%, explosion up 20%", "Урон +30%, взрыв +20%")
	_add(&"fb_lv3", "Damage up 60%, explosion up 40%", "Урон +60%, взрыв +40%")
	_add(&"fb_lv4", "Damage up 100%, explosion up 70%, pierces 1 more", "Урон +100%, взрыв +70%, пробивает ещё 1")
	_add(&"fb_lv5", "Damage up 160%, explosion up 100%, +1 projectile", "Урон +160%, взрыв +100%, +1 снаряд")

	_add(&"oa_lv1", "Arcane blades orbit the caster, slicing nearby enemies", "Тайные клинки вращаются вокруг мага, разрезая ближних врагов")
	_add(&"oa_lv2", "Damage up 30%, blades spin faster", "Урон +30%, клинки вращаются быстрее")
	_add(&"oa_lv3", "Damage up 60%, +1 blade", "Урон +60%, +1 клинок")
	_add(&"oa_lv4", "Damage up 100%, +2 blades", "Урон +100%, +2 клинка")
	_add(&"oa_lv5", "Damage up 150%, +3 blades", "Урон +150%, +3 клинка")

	_add(&"ls_lv1", "A lightning bolt strikes from the sky onto the nearest foe", "Молния бьёт с неба по ближайшему врагу")
	_add(&"ls_lv2", "Damage up 25%", "Урон +25%")
	_add(&"ls_lv3", "Damage up 50%, +1 lightning strike", "Урон +50%, +1 молния")
	_add(&"ls_lv4", "Damage up 80%", "Урон +80%")
	_add(&"ls_lv5", "Damage up 120%, +1 lightning strike", "Урон +120%, +1 молния")

	_add(&"cy_lv1", "Unleashes a spinning vortex that flies toward enemies and grows", "Выпускает вращающийся вихрь, летящий к врагам и увеличивающийся")
	_add(&"cy_lv2", "Damage up 40%, area up 20%, spins faster", "Урон +40%, зона +20%, вращение быстрее")
	_add(&"cy_lv3", "Damage up 80%, area up 40%, +1 arc", "Урон +80%, зона +40%, +1 дуга")
	_add(&"cy_lv4", "Damage up 130%, area up 70%, +1 arc", "Урон +130%, зона +70%, +1 дуга")
	_add(&"cy_lv5", "Damage up 200%, area up 100%, +2 arcs", "Урон +200%, зона +100%, +2 дуги")

	_add(&"ar_lv1", "Emits a powerful arcane ray in a random direction, piercing all", "Испускает мощный тайный луч в случайном направлении, пронзая всех")
	_add(&"ar_lv2", "Damage up 30%, beam wider", "Урон +30%, луч шире")
	_add(&"ar_lv3", "Damage up 60%, +1 ray", "Урон +60%, +1 луч")
	_add(&"ar_lv4", "Damage up 100%, beam 70% wider", "Урон +100%, луч на 70% шире")
	_add(&"ar_lv5", "Damage up 150%, 3 rays", "Урон +150%, 3 луча")

	_add(&"ez_lv1", "Creates a crackling electric field around the caster, shocking foes", "Создаёт потрескивающее электрическое поле вокруг мага, шокируя врагов")
	_add(&"ez_lv2", "Damage +25%, +15% area", "Урон +25%, зона +15%")
	_add(&"ez_lv3", "Damage +50%, +30% area, +1 arc", "Урон +50%, зона +30%, +1 дуга")
	_add(&"ez_lv4", "Damage +80%, +50% area", "Урон +80%, зона +50%")
	_add(&"ez_lv5", "Damage +120%, +75% area, +2 arcs", "Урон +120%, зона +75%, +2 дуги")

	_add(&"sp_lv1", "A hovering spirit orb fires bolts at enemies within range", "Парящий дух стреляет снарядами по врагам в радиусе")
	_add(&"sp_lv2", "Damage up 30%, +1 spirit", "Урон +30%, +1 дух")
	_add(&"sp_lv3", "Damage up 60%, +1 spirit", "Урон +60%, +1 дух")
	_add(&"sp_lv4", "Damage up 100%, faster chain fire", "Урон +100%, быстрее залп")
	_add(&"sp_lv5", "Damage up 150%, +1 spirit", "Урон +150%, +1 дух")

	_add(&"sh_lv1", "Conjures a protective shield that absorbs hits and recharges over time", "Создаёт защитный щит, поглощающий удары и перезаряжающийся со временем")
	_add(&"sh_lv2", "Shield recharges faster", "Щит перезаряжается быстрее")
	_add(&"sh_lv3", "+1 shield charge, faster recharge", "+1 заряд щита, быстрее перезарядка")
	_add(&"sh_lv4", "Shield recharges much faster", "Щит перезаряжается намного быстрее")
	_add(&"sh_lv5", "+1 shield charge, recharge speed doubled", "+1 заряд щита, перезарядка в 2 раза быстрее")

	_add(&"fbr_lv1", "Unleashes a cone of layered flame — a living ёлочка of fire", "Выпускает конус слоистого пламени — живую ёлочку из огня")
	_add(&"fbr_lv2", "Damage up 40%, range up 15%", "Урон +40%, дальность +15%")
	_add(&"fbr_lv3", "Damage up 80%, range up 30%, wider cone", "Урон +80%, дальность +30%, шире конус")
	_add(&"fbr_lv4", "Damage up 130%, range up 50%, much wider", "Урон +130%, дальность +50%, намного шире")
	_add(&"fbr_lv5", "Damage up 200%, range up 80%, blazing cone", "Урон +200%, дальность +80%, пылающий конус")

	_add(&"ndl_lv1", "Fires a concentrated beam of silvery needles at enemies", "Выпускает концентрированный луч серебряных игл во врагов")
	_add(&"ndl_lv2", "Damage up 40%, range up 15%", "Урон +40%, дальность +15%")
	_add(&"ndl_lv3", "Damage up 80%, range up 30%, wider spread", "Урон +80%, дальность +30%, шире разброс")
	_add(&"ndl_lv4", "Damage up 130%, range up 50%, much wider", "Урон +130%, дальность +50%, намного шире")
	_add(&"ndl_lv5", "Damage up 200%, range up 80%, needle storm", "Урон +200%, дальность +80%, шторм игл")

	_add(&"ppl_lv1", "Spawns a toxic green puddle that damages enemies standing in it", "Создаёт ядовитую зелёную лужу, наносящую урон врагам внутри")
	_add(&"ppl_lv2", "Damage up 25%, area up 20%", "Урон +25%, зона +20%")
	_add(&"ppl_lv3", "Damage up 50%, area up 30%, tick faster", "Урон +50%, зона +30%, тики чаще")
	_add(&"ppl_lv4", "Damage up 80%, area up 40%, ticks even faster", "Урон +80%, зона +40%, тики ещё чаще")
	_add(&"ppl_lv5", "Damage up 120%, area up 60%, rapid poison", "Урон +120%, зона +60%, стремительный яд")

	_add(&"fn_lv1", "Expanding frost ring, freezes 2s", "Расширяющееся ледяное кольцо, заморозка 2с")
	_add(&"fn_lv2", "Damage +25%, area +20%", "Урон +25%, зона +20%")
	_add(&"fn_lv3", "Damage +50%, area +30%, freeze +0.3s", "Урон +50%, зона +30%, заморозка +0.3с")
	_add(&"fn_lv4", "Damage +80%, area +40%", "Урон +80%, зона +40%")
	_add(&"fn_lv5", "Damage +120%, area +60%, freeze +0.5s", "Урон +120%, зона +60%, заморозка +0.5с")

	_add(&"boost_max_hp", "Vitality Stone", "Камень жизненной силы")
	_add(&"boost_move_speed", "Swift Boots", "Ботинки скорости")
	_add(&"boost_magic_power", "Arcane Focus", "Магический фокус")
	_add(&"boost_cd_reduction", "Haste Rune", "Руна ускорения")
	_add(&"boost_hp_regen", "Regrowth Seed", "Семя регенерации")
	_add(&"boost_pickup_range", "Magnet Charm", "Магнитный талисман")
	_add(&"boost_spell_duration", "Time Crystal", "Кристалл времени")
	_add(&"boost_crit_chance", "Precision Lens", "Линза точности")
	_add(&"boost_crit_damage", "Critical Gem", "Критический самоцвет")
	_add(&"boost_area_multiplier", "Expansion Orb", "Шар расширения")
	_add(&"boost_mana_gain", "Wisdom Tome", "Книга мудрости")
	_add(&"boost_desc_max_hp", "Increases maximum HP by 20%", "Увеличивает макс. здоровье на 20%")
	_add(&"boost_desc_move_speed", "Increases movement speed by 10%", "Увеличивает скорость передвижения на 10%")
	_add(&"boost_desc_magic_power", "Increases all spell damage by 15%", "Увеличивает урон всех заклинаний на 15%")
	_add(&"boost_desc_cd_reduction", "Reduces spell cooldowns by 3%", "Сокращает перезарядку заклинаний на 3%")
	_add(&"boost_desc_hp_regen", "Regenerates +0.1 HP per second", "Восстанавливает +0.1 ОЗ в секунду")
	_add(&"boost_desc_pickup_range", "Increases pickup radius by 25%", "Увеличивает радиус сбора предметов на 25%")
	_add(&"boost_desc_spell_duration", "Extends spell duration by 5%", "Увеличивает длительность заклинаний на 5%")
	_add(&"boost_desc_crit_chance", "Increases critical hit chance by 3%", "Увеличивает шанс критического удара на 3%")
	_add(&"boost_desc_crit_damage_mult", "Increases critical damage by 10%", "Увеличивает урон критического удара на 10%")
	_add(&"boost_desc_area_multiplier", "Increases spell area by 5%", "Увеличивает область заклинаний на 5%")
	_add(&"boost_desc_mana_gain", "Increases XP gain by 8%", "Увеличивает получение опыта на 8%")

	_add(&"class_select_title", "CHOOSE CLASS", "ВЫБОР КЛАССА")
	_add(&"class_select_subtitle", "Select your champion", "Выберите своего чемпиона")
	_add(&"class_unlock", "Unlock (500)", "Открыть (500)")
	_add(&"class_all_unlocked", "All unlocked!", "Все открыты!")
	_add(&"class_arcanist", "Arcanist", "Арканист")
	_add(&"class_arcanist_desc", "+1 projectile, -10% cooldown", "+1 снаряд, -10% кд")
	_add(&"class_pyromancer", "Pyromancer", "Пиромант")
	_add(&"class_pyromancer_desc", "+20% damage, +15% area", "+20% урон, +15% область")
	_add(&"class_orbiter", "Orbiter", "Орбитант")
	_add(&"class_orbiter_desc", "+1 projectile, +10% damage", "+1 снаряд, +10% урон")
	_add(&"class_stormcaller", "Stormcaller", "Зов Молнии")
	_add(&"class_stormcaller_desc", "+25% damage, -15% cooldown", "+25% урон, -15% кд")
	_add(&"class_typhoon", "Typhoon", "Тайфун")
	_add(&"class_typhoon_desc", "+10% damage, +20% duration", "+10% урон, +20% длительность")
	_add(&"class_raycaster", "Raycaster", "Лучник")
	_add(&"class_raycaster_desc", "+20% damage, +10% width", "+20% урон, +10% ширина")
	_add(&"class_electromant", "Electromant", "Электромант")
	_add(&"class_electromant_desc", "+15% damage, +25% area", "+15% урон, +25% область")
	_add(&"class_spiritcaller", "Spiritcaller", "Духопризыватель")
	_add(&"class_spiritcaller_desc", "+1 spirit, +10% damage", "+1 дух, +10% урон")
	_add(&"class_guardian", "Guardian", "Страж")
	_add(&"class_guardian_desc", "+20% shield HP, +Magic Bolt", "+20% HP щита, +Magic Bolt")
	_add(&"class_breathweaver", "Breathweaver", "Дыхание")
	_add(&"class_breathweaver_desc", "+15% damage, +20% duration", "+15% урон, +20% длительность")
	_add(&"class_needlemancer", "Needlemancer", "Шиповник")
	_add(&"class_needlemancer_desc", "+1 projectile, +20% damage", "+1 снаряд, +20% урон")
	_add(&"class_venomist", "Venomist", "Веномант")
	_add(&"class_venomist_desc", "+25% area, +15% damage", "+25% область, +15% урон")
	_add(&"class_frostcall", "Frostcall", "Морозец")
	_add(&"class_frostcall_desc", "+20% damage, +15% area", "+20% урон, +15% область")

func _add(key: StringName, en: String, ru: String) -> void:
	_translations[key] = {&"en": en, &"ru": ru}
